### ISSUE TITLE
怎么用gpu进行推理？

### ISSUE THREAD

**Issue by AmamiyaRenn** [Z-Xiong/LightTrack-ncnn#10]
#if NCNN_VULKAN and USE_GPU
    std::cout << NCNN_VULKAN << std::endl;
    ex_backbone.set_vulkan_compute(true);
#endif

//    net_init.opt.use_vulkan_compute= true;
//    net_init.set_vulkan_device(0);
    net_init.opt.use_fp16_packed = true;
    net_init.opt.use_fp16_storage = true;
    net_init.opt.use_fp16_arithmetic = true;
    net_init.opt.use_int8_storage = true;
    net_backbone.opt.use_fp16_packed = true;
    net_backbone.opt.use_fp16_storage = true;
    net_backbone.opt.use_fp16_arithmetic = true;
    net_backbone.opt.use_int8_storage = true;
    net_neck_head.opt.use_fp16_packed = true;
    net_neck_head.opt.use_fp16_storage = true;
    net_neck_head.opt.use_fp16_arithmetic = true;
    net_neck_head.opt.use_int8_storage = true;

我增加了这些部分，但gpu推理失败了
错误信息为
compile spir-v module failed
ERROR: 0:10: 'constant_id' : only allowed when generating SPIR-V 
ERROR: 0:10: '' : compilation terminated 
ERROR: 2 compilation errors.  No code generated.

出错位置为
ex_backbone.extract("output.1", xf);

**Comment by Z-Xiong** [comment]
gpu推理的出问题可以咨询ncnn

**Comment by AmamiyaRenn** [comment]
> 

大佬你的代码是没有带gpu的吗，我用cpu可以跑

**Comment by Z-Xiong** [comment]
> > 
> 
> 大佬你的代码是没有带gpu的吗，我用cpu可以跑

我也没跑起来gpu的，你可以按照报错给ncnn提下issue
