### ISSUE TITLE
是否进行过量化

### ISSUE THREAD

**Issue by 20XYSong** [Z-Xiong/LightTrack-ncnn#11]
大佬你好，我想请问下您这个项目里面是对LightTrack的三部分模型都做了int8量化吗？

**Comment by Z-Xiong** [comment]
没有呢，只是float32的

**Comment by 20XYSong** [comment]
> 

好的，感谢~
另外想请教下，追踪模型是不是不太适合做后量化呀

**Comment by Z-Xiong** [comment]
> > 
> 
> 好的，感谢~ 另外想请教下，追踪模型是不是不太适合做后量化呀

没试过哈，你可以试一下，我是用来跑在瑞芯微npu上的，npu上我用了混合量化，效果还可以。

**Comment by zjd1988** [comment]
@Z-Xiong 你好，你是在哪个瑞芯微芯片上进行的混合量化呢，速度怎么样呢？

**Comment by Z-Xiong** [comment]
> @Z-Xiong 你好，你是在哪个瑞芯微芯片上进行的混合量化呢，速度怎么样呢？

rv1109，算力1.2T，150ms左右

**Comment by zjd1988** [comment]
@Z-Xiong 嗯嗯，谢谢啦。
