### ISSUE TITLE
按照教程转pth为onnx格式，报错Process finished with exit code 132 (interrupted by signal 4: SIGILL)

### ISSUE THREAD

**Issue by YinsTH** [Z-Xiong/LightTrack-ncnn#13]
您好，我在替换了lib/models/super_model_DP.py和tracking/torch2onnx.py后，无论是转换backbone还是neck_head模型，程序都会在torch.onnx.export内突然结束，没有明显的报错，只有Process finished with exit code 132 (interrupted by signal 4: SIGILL)，前面的读模型都是正常的，也能print(siam_net)
super_model_DP.py代码
![Screenshot from 2022-10-27 22-31-41](https://user-images.githubusercontent.com/98153869/198315462-dc310d8f-ffb5-4e17-bbb8-198beb2a681a.png)
torch2onnx.py代码
![Screenshot from 2022-10-27 22-33-05](https://user-images.githubusercontent.com/98153869/198315866-fb514446-1691-4db3-a6f2-03a85e28862b.png)
运行结果
![Screenshot from 2022-10-27 22-34-13](https://user-images.githubusercontent.com/98153869/198316471-91753eba-df06-4522-ae4a-824443fdfda9.png)

我通过单步调试发现程序在F.conv2d()函数内突然中止了，不清楚是否跟我的LightTrack环境有关，我没有完全安装官方的安装脚本的库，只装了pytorch，cuda，cudnn，torchvision等转换格式必要的库，因为按照官方脚本有些库装不上。
如能解答，不胜感激

**Comment by YinsTH** [comment]
解决了，不能按照LightTrack官方的说明安装pytorch 1.1.0的版本，用作者的另一个项目stark的环境，pytorch版本是1.7.0的就可以正常转换为onnx了

**Comment by Z-Xiong** [comment]
不好意思，才看到，解决了就好。

**Comment by YinsTH** [comment]
谢谢大佬！我也在移植LightTrack到瑞芯微的rv1126上，我这边跑起来帧率最快20帧，实际结合摄像头的话只有16帧左右，但是backbone部分在NPU运行时间是波动的，从30ms涨到60ms，导致跑一会儿以后只有10帧，想问下大佬有这方面问题吗

Toy ***@***.***> 于2022年11月16日周三 18:37写道：

**Comment by YinsTH** [comment]
打扰啦，方便的话可以加个微信吗，谢谢大佬😁

tianhao yin ***@***.***> 于2022年11月16日周三 19:00写道：

**Comment by Z-Xiong** [comment]
我是跑在rv1109上的，你是单独运行demo跑的还是和有跑其他程序呢?一般来说是比较稳定的，在rv1109上我的速度是这样的：


量化\耗时(ms) | lighttrack_init | lighttrack_backbone | ighttrack_neckhead
-- | -- | -- | --
全量化 | 7 | 30 | 25
默认混合量化 | 20 | 103 | 25

**Comment by Z-Xiong** [comment]
微信x545690660

**Comment by YinsTH** [comment]
单独运行demo，跑几百张测试图片，时间还比较稳定，我的rknn全量化模型精度较低，只能部分层使用混合量化，跟您全量化的各部分时间基本一致。我这边还要结合摄像头跑实际的场景，按理说开摄像头不应该影响NPU速度，但我这摄像头一开推理时间就要加倍……

Toy ***@***.***> 于2022年11月17日周四 14:57写道：

**Comment by YinsTH** [comment]
感谢感谢

Toy ***@***.***> 于2022年11月17日周四 15:01写道：

**Comment by zjd1988** [comment]
@YinsTH 你好，lighttrack在rv1126实际部署的最终效果和指标怎么样，打算后边在1126上试试？
