### ISSUE TITLE
你好大佬，我打开跑这个模型在rk3588开发板上。

### ISSUE THREAD

**Issue by AAAAAAAAw** [Z-Xiong/LightTrack-ncnn#14]
请问能加个联系方式吗。
想问下，官方训练好的模型是那个模型。

We have uploaded the pre-trained weights of the SuperNets(for both ImageNet classification and object tracking) to [Google Drive](https://drive.google.com/drive/folders/1HXhdJO3yhQYw3O7nGUOXHu2S20Bs8CfI). Users can use them as initialization for future research on efficient object tracking.

是网盘提供的这个文件吗。

**Comment by Z-Xiong** [comment]
原始模型是pytorch的，我转为了ncnn，rk的话如果有npu可以转成rknn

**Comment by Z-Xiong** [comment]
就是网盘这个，具体如何把官方模型转为ncnn模型，我的readme里有教程。

**Comment by AAAAAAAAw** [comment]
大佬转 ncnn 跑的是  android 吗？
大佬，你后面还有自己另外训练吗? 能提供训练代码嘛。

**Comment by Z-Xiong** [comment]
我是跑的arm linux，没有自己训练，lighttrack的结构是通过NAS出来的，官方也没提供训练代码呀。

**Comment by Z-Xiong** [comment]
不过你可以根据https://github.com/visionml/pytracking/tree/master/pytracking，把lighttrack的结构放进去，训练就可以了。我自己是这样做的，因为lighttrack对我来说还是太大了，所以也做了个小的。

**Comment by Z-Xiong** [comment]
微信x545690660

**Comment by Z-Xiong** [comment]
rk3588的npu有6T的计算能力呢！直接干npu啊

**Comment by YinsTH** [comment]
> 就是网盘这个，具体如何把官方模型转为ncnn模型，我的readme里有教程。

官方项目里的snapshot文件夹里有个他们训练的LightTrackM.pth模型诶，只有8M左右，但是不是按自己训练精度会高点？
