### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Naughty-Galileo** [Z-Xiong/LightTrack-ncnn#15]
大佬您好，我按照您的步骤去做了，出现了以下问题
1、显示没有vulkan头文件。我将压缩包里的include头文件复制过去解决了这个问题。
2、上一步解决过后，还是编译错误，libopencv_world.so链接报错。请问是哪里有问题呢？

**Comment by Z-Xiong** [comment]
应该是动态库的支持问题，我的是ubuntu20.04编译出来的，你可能需要重新编译一下opencv

**Comment by Naughty-Galileo** [comment]
> 一步解决过后，还是编译错误，libopencv_world.so链接报错。请问是哪里有问题呢？

好的 谢谢！
