### ISSUE TITLE
ncnn

### ISSUE THREAD

**Issue by Cydia2018** [Z-Xiong/LightTrack-ncnn#2]
您好，想问您仓库中的预训练模型是从[官方仓库](https://github.com/researchmm/LightTrack)中导出的吗？

**Comment by Z-Xiong** [comment]
> 您好，想问您仓库中的预训练模型是从[官方仓库](https://github.com/researchmm/LightTrack)中导出的吗？

是的

**Comment by Cydia2018** [comment]
> > 您好，想问您仓库中的预训练模型是从[官方仓库](https://github.com/researchmm/LightTrack)中导出的吗？
> 
> 是的

可以上传导出ONNX文件部分的代码吗？感谢。

**Comment by Z-Xiong** [comment]
> > > 您好，想问您仓库中的预训练模型是从[官方仓库](https://github.com/researchmm/LightTrack)中导出的吗？
> > 
> > 
> > 是的
> 
> 可以上传导出ONNX文件部分的代码吗？感谢。

导出onnx需要修改模型inference部分，这个我还没有整理

**Comment by Cydia2018** [comment]
> > > > 您好，想问您仓库中的预训练模型是从[官方仓库](https://github.com/researchmm/LightTrack)中导出的吗？
> > > 
> > > 
> > > 是的
> > 
> > 
> > 可以上传导出ONNX文件部分的代码吗？感谢。
> 
> 导出onnx需要修改模型inference部分，这个我还没有整理

好的，感谢 ;)

**Comment by Z-Xiong** [comment]
@Cydia2018 


[torch2onnx.zip](https://github.com/Z-Xiong/LightTrack-ncnn/files/7768144/torch2onnx.zip)

1】解压附件
2】cp super_model_DP.py LightTrack/lib/models/super_model_DP.py
3】cp torch2onnx.py LightTrack/tracking/torch2onnx.py

对于转为onnx模型，主要关注Super_model_DP_retrain这个类中的forward函数，需要导出三个模型，三次导出依次init，backbone和neck_head，
（1）模型推理时对应代码如下（在LightTrack/lib/models/super_model_DP.py），根据模型的不同选择注释掉其他的forward函数
    # def forward(self, z):   # init  or backbone
    #     self.zf = self.features(z)
    #     return self.zf


    # def forward(self, zf, xf):   # neck and head
    #     # BN before Pointwise Corr
    #     zf, xf = self.neck(zf, xf)
    #     # Point-wise Correlation
    #     feat_dict = self.feature_fusor(zf, xf)
    #     # supernet head
    #     oup = self.head(feat_dict)
    #     return oup['cls'], oup['reg']
（2）对应的torch2onnx.py 也是分三个模型导出，需要修改的地方如下（LightTrack/tracking/torch2onnx.py），也是根据模型的不同，修改代码，这里的修改需要与super_model_DP.py的foward函数对应

    # # convert init-net
    # x = torch.randn(1, 3, 127, 127)
    # input_names = ["input1"]
    # output_names = ["output.1"]
    # # fix shape
    # torch.onnx.export(siam_net, x, "lighttrack_init.onnx", verbose=True, input_names=input_names,
    #                   output_names=output_names)
    #
    # # convert backone-net
    # x = torch.randn(1, 3, 288, 288)
    # input_names = ["input1"]
    # output_names = ["output.1"]
    # # fix shape
    # torch.onnx.export(siam_net, x, "lighttrack_backbone.onnx", verbose=True, input_names=input_names,
    #                   output_names=output_names)


    # convert neck head
    zf = torch.randn(1, 96, 8, 8)
    xf = torch.randn(1, 96, 18, 18)
    input_names = ["input1"] + ["input2"]
    output_names = ["output.1"] + ["output.2"]
    # fix shape
    torch.onnx.export(siam_net, (zf, xf), "lighttrack_neck_head.onnx", verbose=True, input_names=input_names, output_names=output_names)



转换参数：
$ python torch2onnx.py --arch LightTrackM_Subnet --resume LightTrack/snapshot/LightTrackM/LightTrackM.pth --stride 16 --path_name back_04502514044521042540+cls_211000022+reg_100000111_ops_32

**Comment by Cydia2018** [comment]
> @Cydia2018
> 
> [torch2onnx.zip](https://github.com/Z-Xiong/LightTrack-ncnn/files/7768144/torch2onnx.zip)
> 
> 1】解压附件 2】cp super_model_DP.py LightTrack/lib/models/super_model_DP.py 3】cp torch2onnx.py LightTrack/tracking/torch2onnx.py
> 
> 对于转为onnx模型，主要关注Super_model_DP_retrain这个类中的forward函数，需要导出三个模型，三次导出依次init，backbone和neck_head， （1）模型推理时对应代码如下（在LightTrack/lib/models/super_model_DP.py），根据模型的不同选择注释掉其他的forward函数
> 
> ```
>     # def forward(self, z):   # init 
>     #     self.zf = self.features(z)
>     #     return self.zf
> 
>     # def forward(self, x):   # backbone
>     #     self.xf = self.features(x)
>     #     return self.xf
> 
>     # def forward(self, zf, xf):   # neck and head
>     #     # BN before Pointwise Corr
>     #     zf, xf = self.neck(zf, xf)
>     #     # Point-wise Correlation
>     #     feat_dict = self.feature_fusor(zf, xf)
>     #     # supernet head
>     #     oup = self.head(feat_dict)
>     #     return oup['cls'], oup['reg']'
> ```
> 
> （2）对应的torch2onnx.py 也是分三个模型导出，需要修改的地方如下（LightTrack/tracking/torch2onnx.py），也是根据模型的不同，修改代码，这里的修改需要与super_model_DP.py的foward函数对应
> 
> ```
>     # # convert init-net
>     # x = torch.randn(1, 3, 127, 127)
>     # input_names = ["input1"]
>     # output_names = ["output.1"]
>     # # fix shape
>     # torch.onnx.export(siam_net, x, "lighttrack_init.onnx", verbose=True, input_names=input_names,
>     #                   output_names=output_names)
>    
>     # # convert backone-net
>     # x = torch.randn(1, 3, 288, 288)
>     # input_names = ["input1"]
>     # output_names = ["output.1"]
>     # # fix shape
>     # torch.onnx.export(siam_net, x, "lighttrack_backbone.onnx", verbose=True, input_names=input_names,
>     #                   output_names=output_names)
> 
> 
>     # convert neck head
>     # zf = torch.randn(1, 96, 8, 8)
>     # xf = torch.randn(1, 96, 18, 18)
>     # input_names = ["input1"] + ["input2"]
>     # output_names = ["output.1"] + ["output.2"]
>     #  # fix shape
>     # torch.onnx.export(siam_net, (zf, xf), "lighttrack_neck_head.onnx", verbose=True, input_names=input_names, output_names=output_names)
> ```
> 
> 转换参数：
> 
> ```
> $ python torch2onnx.py --arch LightTrackM_Subnet --resume LightTrack/snapshot/LightTrackM/LightTrackM.pth --stride 16 --path_name back_04502514044521042540+cls_211000022+reg_100000111_ops_32
> ```

十分感谢您的帮助！

**Comment by Z-Xiong** [comment]
- [ ] update README.md #4

**Comment by Cydia2018** [comment]
请问作者，pscore_window max score一直为nan，可能的原因是什么

**Comment by Z-Xiong** [comment]
> 请问作者，pscore_window max score一直为nan，可能的原因是什么

用的我的模型跑的么？

**Comment by Cydia2018** [comment]
> > 请问作者，pscore_window max score一直为nan，可能的原因是什么
> 
> 用的我的模型跑的么？

是的 :(

**Comment by Z-Xiong** [comment]
> > > 请问作者，pscore_window max score一直为nan，可能的原因是什么
> > 
> > 
> > 用的我的模型跑的么？
> 
> 是的 :(

你再拉我最新的代码，跑一下，看看行不行。
