### ISSUE TITLE
pscore_window max score一直为nan

### ISSUE THREAD

**Issue by HonglinChu** [Z-Xiong/LightTrack-ncnn#7]
你好,我这里遇到如下的报错:
Update stage ---- output cls_score and bbox_pred extracting cost time : 6 ms
Update stage ---- postprocess cost time : 0 ms
pscore_window max score is: nan

通过单步调试发现,  **cls_score_data**, **bbox_pred_data1,bbox_pred_data2, bbox_pred_data3, bbox_pred_data4**都是 NaN

`  float* **cls_score_data** = (float*)cls_score.data;
    cls_score_sigmoid.clear();

    int cols = cls_score.w;
    int rows = cls_score.h;

    for (int i = 0; i < cols*rows; i++)   // 18 * 18
    {
        cls_score_sigmoid.push_back(sigmoid(cls_score_data[i]));
    }

    std::vector<float> pred_x1(cols*rows, 0), pred_y1(cols*rows, 0), pred_x2(cols*rows, 0), pred_y2(cols*rows, 0);

    float* bbox_pred_data1 = bbox_pred.channel(0);
    float* bbox_pred_data2 = bbox_pred.channel(1);
    float* bbox_pred_data3 = bbox_pred.channel(2);
    float* bbox_pred_data4 = bbox_pred.channel(3);`

难道是在网络的输出地方就出错了?
`    ex_neck_head.extract("output.1", cls_score);  // [c, w, h] = [1, 18, 18]
    ex_neck_head.extract("output.2", bbox_pred); // [c, w, h] = [4, 18, 18]`

**Comment by HonglinChu** [comment]
我的ncnn是目前最新的版本

**Comment by Z-Xiong** [comment]
> 我的ncnn是目前最新的版本

有可能是这个原因，方便把你的ncnn.a文件和头文件放上来，我看一下么？
如果使用我提供的libncnn.a也会出现这个问题么？

**Comment by HonglinChu** [comment]
你好,我是在macos上测试的, 我自己重新编译了ncnn , 版本macos-arm64 架构, 没办法直接用你的libncnn.a . 我测试过ncnn的分类例程是没有问题的.

**Comment by Z-Xiong** [comment]
> 你好,我是在macos上测试的, 我自己重新编译了ncnn , 版本macos-arm64 架构, 没办法直接用你的libncnn.a . 我测试过ncnn的分类例程是没有问题的.

有可能是版本不一致，对应的params文件读取的不一致，输出导致NaN。可以尝试修改params或者，或者使用你的ncnn重新导出一份模型文件。导出模型文件可以参考Readme

**Comment by HonglinChu** [comment]
> > 你好,我是在macos上测试的, 我自己重新编译了ncnn , 版本macos-arm64 架构, 没办法直接用你的libncnn.a . 我测试过ncnn的分类例程是没有问题的.
> 
> 有可能是版本不一致，对应的params文件读取的不一致，输出导致NaN。可以尝试修改params或者，或者使用你的ncnn重新导出一份模型文件。导出模型文件可以参考Readme

你好, 我按照你的方式重新导入生成param和bin, 输入和输入维度都没问,就是输出内容为NaN
